# SConstruct initializing
import os
Import('env')

# Cloning compile environment
lbfgs = env.Clone()

#-- Objective C environment
envc = Environment(ENV=os.environ, CC = 'gcc', CXX='g++') 
envc.Append(CPPFLAGS=' -O3 -Wall' ) # Optimized 
#envc.Append(CPPFLAGS=' -g -Wall' ) # For debugging

# Setup
libdir = '../build/'

#  Library
lbfgs_lib = 'lbfgs.c'
libmains = Split(lbfgs_lib)

envc.Library(libdir + 'lbfgs', libmains)
