# SConstruct initializing
import os
Import('env')
Import('envc')
	
builddir = '../build/'

# Adding library path
envc.Append(CPPPATH=['../include'])

# Library
rsfc = envc.Library(builddir + 'rsfc', ['file.c','getpar.c', 'alloc.c', 'error.c', 'simtab.c', 'komplex.c', 'c99.c', 'kiss_fft.c'])
rsfcpp = env.Library(builddir + 'rsfcpp', ['rsf.cpp'], LIBS=['rsfc'])
