# SConstruct initializing
import os
Import('env')
	
# Cloning environments for different compilers
mpi = env.Clone(CC='mpicc', CXX='mpicxx')

builddir = '../build/'

# Library
env.Library(builddir + 'rsfcpp', ['rsf.cpp','file.c','getpar.c', 'alloc.c', 'error.c', 'simtab.c', 'komplex.c', 'c99.c', 'kiss_fft.c'])
