# SConstruct initializing
import os
Import('env')
	
builddir = '../build/'


#-- Objective C environment
envc = Environment(ENV=os.environ, CC = 'gcc', CXX='g++') 
envc.Append(CPPFLAGS=' -O3 -Wall' ) # Optimized 
#envc.Append(CPPFLAGS=' -g -Wall' ) # For debugging
#
envc.Append(CPPPATH=['../include'])

# Library
rsfc = envc.Library(builddir + 'rsfc', ['file.c','getpar.c', 'alloc.c', 'error.c', 'simtab.c', 'komplex.c', 'c99.c', 'kiss_fft.c'])
rsfcpp = env.Library(builddir + 'rsfcpp', ['rsf.cpp'], LIBS=['rsfc'])
