# SConstruct initializing
import os
Import('env')

# Cloning compile environment
gui = env.Clone()

# Setup
prefix = env['program_prefix']
srcdir = './src/'
libdir = './lib/'
mainlibdir = '../lib/'
bindir = '../bin/'

if(env['WX']):
    # Getting platform dependent flags using wx-config
    gui.ParseConfig('/Users/wiktorweibull/software/wxWidgets-3.0.2/build-release/wx-config --cxxflags --libs')

	# Where are the files 
    gui.Append(CPPPATH=['./lib', './include', './shared'])

    hello_gui = gui.Program(srcdir + prefix + 'hello_gui',[srcdir + 'hello_gui.cpp',libdir + 'mainframe.cpp'])
    gui.Install(bindir,hello_gui)

    gui.Append(LIBS=['file', 'sort', 'utils', 'geometry', 'data', 'fft'])
    image = gui.Program(srcdir + prefix + 'image',[srcdir + 'image.cpp',libdir + 'image2dframe.cpp', libdir + 'image3dframe.cpp', libdir + 'zoom.cpp', libdir + 'picks.cpp', libdir + 'colors.cpp'])
    gui.Install(bindir,image)

    cipmute = gui.Program(srcdir + prefix + 'cipmute',[srcdir + 'cipmute.cpp',libdir + 'image2dframe.cpp', libdir + 'zoom.cpp', libdir + 'picks.cpp', libdir + 'colors.cpp'])
    gui.Install(bindir,cipmute)

    fbpick2d = gui.Program(srcdir + prefix + 'fbpick2d',[srcdir + 'fbpick2d.cpp',libdir + 'image2dframe.cpp', libdir + 'zoom.cpp', libdir + 'picks.cpp', libdir + 'colors.cpp'])
    gui.Install(bindir,fbpick2d)

    fbpick3d = gui.Program(srcdir + prefix + 'fbpick3d',[srcdir + 'fbpick3d.cpp',libdir + 'image2dframe.cpp', libdir + 'zoom.cpp', libdir + 'picks.cpp', libdir + 'colors.cpp'])
    gui.Install(bindir,fbpick3d)
